version: "3.9"

services:
    frontend:
        build: ./frontend
        container_name: production_frontend

    backend:
        build: ./com.DataConsolidation
        container_name: production_backend

    proxy:
        image: nginx:latest
        container_name: production_nginx
        ports:
            - 80:80
        volumes:
            - ./nginx:/etc/nginx
